### ISSUE TITLE
Plugin source

### ISSUE THREAD

**Issue by golenkovm** [clickviewapp/moodle-atto_clickview#1]
Hi team,

Could someone please advise regarding best plugin course?

As I can see plugins could be downloaded either from https://www.clickview.com.au/plugins/moodle/#au or from this github repo. However, plugin code look a bit different. Which one should be considered as the most recent?

Kind regards,
Misha

**Comment by Shalelol** [comment]
Hey Misha,

The plugin in this repository is the most recent version.

It can also be found in Moodle's plugin directory here: https://moodle.org/plugins/atto_clickview, if you'd like to install it directly via Moodle.

Regards,
Shale
